### ISSUE TITLE
[BUG] Windows code ignores cancel on open/save dialogs.

### ISSUE THREAD

**Issue by rj45** [tseli0s/nvdialog#54]
The return value of the following functions is ignored, which is a BOOL indicating if the ok button was pressed, or cancel/close:

https://github.com/tseli0s/nvdialog/blob/c35acb97ad1ee3c3573e3bbf1155a6a52cd5649d/src/backend/win32/nvdialog_file_dialog.c#L104-L105

I fixed it like this, but you may want to do it differently:

```c
  if (dialog->is_save_dialog)
    dialog->location_was_chosen = GetSaveFileName(&ofn);
  else
    dialog->location_was_chosen = GetOpenFileName(&ofn);
```

I then check `dialog->location_was_chosen` before I `strdup()` the string and return it. That way the string doesn't need to be freed if `dialog->location_was_chosen` is false.

**Comment by tseli0s** [comment]
That fix seems fine, make a pull request and I'll merge it.
