### ISSUE TITLE
[BUG] Double free crash on Mac

### ISSUE THREAD

**Issue by rj45** [tseli0s/nvdialog#55]
The following line causes the dialog to be freed:

https://github.com/tseli0s/nvdialog/blob/c35acb97ad1ee3c3573e3bbf1155a6a52cd5649d/src/backend/cocoa/nvdialog_file_dialog.m#L57

If ARC is enabled (automatic reference counting), then when the function exits, the dialog will be freed again, resulting in a double free crash. I am using another library that requires that ARC be enabled, so I can't just disable it. I have no idea if there's a way to detect at compile time whether ARC is enabled or not. Hopefully there is.

At any rate, I just copied the library locally and fixed it in my copy, so no urgency on a fix, I just thought I would let you know.

**Comment by tseli0s** [comment]
Being fairly honest here, I know nothing about neither C-Obj or MacOS. @Frityet implemented the backend but since he hasn't committed since and I don't have anything to test the backend on, I just hope that once the code compiles it works fine.

In fact, back a few months ago, I had to rework some parts of the library and since there were no maintainers to handle the changes in the macOS backend, I was left to rewrite the necessary parts by hand. In fact there are tens of commits where I had to fix silly compiling errors because I didn't know any Obj-C.

Feel free to contribute any fixes, it's even in the README that the `macOS` backend is lacking contributors :)

**Comment by Frityet** [comment]
> The following line causes the dialog to be freed:
> 
> https://github.com/tseli0s/nvdialog/blob/c35acb97ad1ee3c3573e3bbf1155a6a52cd5649d/src/backend/cocoa/nvdialog_file_dialog.m#L57
> 
> If ARC is enabled (automatic reference counting), then when the function exits, the dialog will be freed again, resulting in a double free crash. I am using another library that requires that ARC be enabled, so I can't just disable it. I have no idea if there's a way to detect at compile time whether ARC is enabled or not. Hopefully there is.
> 
> At any rate, I just copied the library locally and fixed it in my copy, so no urgency on a fix, I just thought I would let you know.

The library should be compiled with -fno-arc which won't generate the ARC calls for just the library

@tseli0s ill see what I can do

**Comment by tseli0s** [comment]
Given that ARC will free it anyways if enabled, why not just use it to our advantage? Seems like an easy way to avoid memory leaks anyways.

**Comment by Frityet** [comment]
> Given that ARC will free it anyways if enabled, why not just use it to our advantage? Seems like an easy way to avoid memory leaks anyways.

I just saw that you weren't using ARC in the existing code when I made my PR, so I just matched what was there. ARC is great

**Comment by Frityet** [comment]
> > Given that ARC will free it anyways if enabled, why not just use it to our advantage? Seems like an easy way to avoid memory leaks anyways.
> 
> I just saw that you weren't using ARC in the existing code when I made my PR, so I just matched what was there. ARC is great

Nvm I was thinking of a different project. I have no clue why I didn't use ARC

**Comment by Frityet** [comment]
After doing some review, I remember why. The memory won't be deallocated at all if we only use ARC because the memory is technically owned by C which doesn't have the ARC semantics required. We just need to compile with -fobjc-no-arc

**Comment by tseli0s** [comment]
I'll add the flag on CMakeLists.txt, in the meantime, @rj45 how are you doing on those pull requests you mentioned?

**Comment by tseli0s** [comment]
Seems like 14cb27d will do fine. I'm closing this issue as resolved, if it's still causing a crash reopen and I'll see what I can do.
